---
site_name: "al-linkml-schema"
theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: blue
  features:
    - content.tabs.link
  logo: assets/logo.svg
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
markdown_extensions:
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - assets/style.css
site_url: https://r1tger.github.io/al-linkml-schema
repo_url: https://github.com/r1tger/al-linkml-schema
